export type BlogPost = {
  slug: string;
  title: string;
  date: string;
  readTime: string;
  tag: string;
  excerpt: string;
  body: Array<{ type: "p" | "h2" | "h3" | "table"; text?: string; rows?: string[][]; headers?: string[] }>;
};

export const posts: BlogPost[] = [
  {
    slug: "what-is-l-glutathione",
    title: "What Is L-Glutathione, and Why Is It Called the Master Antioxidant?",
    date: "May 1, 2026",
    readTime: "4 min read",
    tag: "Science",
    excerpt:
      "A clear, science-grounded explanation of glutathione — how it works in the body, why it's central to a brighter complexion, and how to take it well.",
    body: [
      {
        type: "p",
        text: "If you have ever looked into skin brightening, you have almost certainly encountered the word glutathione. It is everywhere — in serums, IV drips, drinkable elixirs, and dermatologists' clinics. But behind the marketing language is a very real, very specific molecule that the human body has been making since long before any of us were born.",
      },
      {
        type: "p",
        text: "This article is a clean, honest look at what L-glutathione actually is, what it does, and how to use it well as part of a daily ritual.",
      },
      { type: "h2", text: "A tripeptide built for protection" },
      {
        type: "p",
        text: "Glutathione is a tripeptide — a small chain of three amino acids: glutamic acid, cysteine, and glycine. It is produced naturally in every cell of your body, with the highest concentrations in the liver, where its job is, simply, to protect.",
      },
      { type: "p", text: "It does that protection in two main ways:" },
      {
        type: "p",
        text: "Neutralising free radicals — the unstable molecules generated by pollution, UV exposure, alcohol, stress and even ordinary metabolism. Left unchecked, these damage proteins, lipids and DNA, accelerating ageing of every tissue, including skin.",
      },
      {
        type: "p",
        text: "Recycling other antioxidants — vitamin C and vitamin E both rely on glutathione to return to their active form after they have done their work. Without enough glutathione, the entire antioxidant network slows down.",
      },
      {
        type: "p",
        text: "This is why researchers call it the master antioxidant. It is not just one player on the team — it keeps the rest of the team on the field.",
      },
      { type: "h2", text: "What does it do for skin?" },
      {
        type: "p",
        text: "Skin is one of the most exposed organs in the body. Every day it absorbs sunlight, friction, and airborne pollutants, and every day it has to repair the damage. The visible signs we associate with ageing — dullness, uneven tone, pigmentation, fine lines — are largely the cumulative cost of that repair lagging behind the damage.",
      },
      { type: "p", text: "Glutathione supports the skin in three observable ways:" },
      {
        type: "p",
        text: "1. Brightening. It inhibits the enzyme tyrosinase, which is the bottleneck in melanin production. Less tyrosinase activity means fewer dark patches and a more even tone, especially in skin types prone to post-inflammatory pigmentation.",
      },
      {
        type: "p",
        text: "2. Defence. Higher intracellular glutathione is associated with stronger resistance to oxidative stress — the underlying driver of premature ageing.",
      },
      {
        type: "p",
        text: "3. Detox support. The liver uses glutathione to bind and clear toxins. A clearer liver tends to show up as clearer skin.",
      },
      { type: "h2", text: "How to take it well" },
      { type: "p", text: "A few practical notes:" },
      {
        type: "p",
        text: "Morning, on an empty stomach. Absorption is highest when the gut is uncomplicated by food.",
      },
      {
        type: "p",
        text: "Consistency over intensity. Glutathione is a daily, cumulative ritual — not a one-off treatment. Most people notice a difference between weeks four and six.",
      },
      {
        type: "p",
        text: "Pair it with collagen. The two work on different layers of the skin — glutathione on tone and oxidative defence, collagen on structure and elasticity. Together they cover the full picture.",
      },
      {
        type: "p",
        text: "Hydrate. Antioxidants do their best work in a well-hydrated body.",
      },
      {
        type: "p",
        text: "That last point is worth dwelling on: there is no supplement, however well-formulated, that will outperform good water intake, good sleep and a varied diet. Glutathione is a multiplier of those habits, not a substitute for them.",
      },
      { type: "h2", text: "A note on form" },
      {
        type: "p",
        text: "You will see glutathione sold in many forms — capsules, IV infusions, lozenges, drinks. The drinkable, liquid form has two practical advantages: the dose is precise, and the molecule is delivered already in solution, which the gut can process without first having to break down a tablet. This is the form we have chosen for GLUTAGE for that reason.",
      },
      {
        type: "p",
        text: "The takeaway is simple. Glutathione is not a beauty trend. It is a foundational molecule your body already produces and depends on. Supplementing it well, alongside collagen and the essential co-factors that keep it active, gives your skin the quiet, daily support it needs to look its luminous best.",
      },
    ],
  },
  {
    slug: "marine-collagen-vs-bovine-collagen",
    title: "Marine Collagen vs Bovine Collagen: Which One Should You Actually Take?",
    date: "April 22, 2026",
    readTime: "3 min read",
    tag: "Guide",
    excerpt:
      "Both work — but they are not interchangeable. A practical comparison of marine and bovine collagen for skin, including absorption, sustainability, and how to choose.",
    body: [
      {
        type: "p",
        text: "Collagen is the most abundant protein in your body. It is the scaffolding of your skin, the cushion in your joints, the firmness of your hair shaft. From about your mid-twenties, your body starts producing measurably less of it each year — and one of the first places that shortfall becomes visible is your face.",
      },
      {
        type: "p",
        text: "That is the simple reason collagen supplements have become a daily ritual for so many people. But once you start shopping for one, you immediately hit a question: marine collagen or bovine collagen?",
      },
      { type: "p", text: "Here is what the science actually says." },
      { type: "h2", text: "They are different fish (literally)" },
      { type: "p", text: "Both marine and bovine collagen are real, useful proteins. They differ in three meaningful ways:" },
      {
        type: "table",
        headers: ["", "Marine Collagen", "Bovine Collagen"],
        rows: [
          ["Source", "Fish skin and scales", "Cow hides and connective tissue"],
          ["Main types", "Type I (skin, hair, nails)", "Types I and III (skin, bone, gut lining)"],
          ["Peptide size", "Smaller — typically 2–5 kDa", "Larger — typically 5–10 kDa"],
          ["Absorption", "Faster, higher bioavailability", "Slower, slightly lower"],
        ],
      },
      {
        type: "p",
        text: "The most important line in that table is the last one. Marine collagen peptides are simply smaller, which means more of what you swallow actually makes it into your bloodstream and reaches the skin, where you want it.",
      },
      { type: "h2", text: "Why this matters for your skin" },
      {
        type: "p",
        text: "Your skin is roughly 80 percent type I collagen by dry weight. Marine collagen is almost exclusively type I, which makes it the most direct match for what your face actually needs.",
      },
      {
        type: "p",
        text: "Bovine collagen is a richer source of type III, which is more important for gut lining and connective tissue. Both are valuable — but if your priority is firmness, elasticity, and that quiet glow, marine collagen is the more targeted choice.",
      },
      { type: "h2", text: "Sustainability and faith concerns" },
      {
        type: "p",
        text: "For our customers in Pakistan, this matters. Marine collagen sourced from wild-caught fish offcuts uses parts of the fish that would otherwise be wasted, has no concerns about bovine origin or processing, and has a lower environmental footprint than cattle-derived collagen.",
      },
      {
        type: "p",
        text: "For households where these things matter, marine is the cleaner default.",
      },
      { type: "h2", text: "How to make it work" },
      { type: "p", text: "Three rules that hold regardless of the source:" },
      {
        type: "p",
        text: "1. Take it daily. Collagen synthesis is a long, slow conversation between your body and the building blocks you give it. Skipping days breaks the conversation.",
      },
      {
        type: "p",
        text: "2. Pair it with vitamin C. Your body cannot assemble collagen without it. This is why GLUTAGE blends both into a single vial — the C is already there.",
      },
      {
        type: "p",
        text: "3. Be patient. Most people see firmness changes between weeks six and twelve, and noticeable elasticity changes after three to four months.",
      },
      {
        type: "p",
        text: "If you remember nothing else, remember this: collagen on its own is a half-finished sentence. It is the cofactors — vitamin C, glutathione, the trace minerals — that let your body turn it into actual skin. Choose a formula that respects that, and the results follow.",
      },
    ],
  },
  {
    slug: "skin-brightening-pakistan-guide",
    title: "Skin Brightening in Pakistan: A Realistic, Dermatologist-Aware Guide",
    date: "April 8, 2026",
    readTime: "4 min read",
    tag: "Skin",
    excerpt:
      "Pakistani skin sits in a unique band of melanin reactivity. This is what actually works for an even tone — and what to avoid — from a science-first perspective.",
    body: [
      {
        type: "p",
        text: "Pakistani skin is beautiful and complicated. It sits in Fitzpatrick types III to V — pigment-rich, melanin-reactive, and quick to respond to the sun, stress and inflammation. That same reactivity that gives our skin its warmth also makes it prone to dark patches, melasma, post-inflammatory hyperpigmentation, and uneven tone.",
      },
      {
        type: "p",
        text: "The market is full of products that promise to fix this in a week. Almost none of them do, and many of them harm the skin in the trying. This is a calmer guide, written for women who want to look their best without ruining their barrier.",
      },
      { type: "h2", text: "First: what brightening actually means" },
      {
        type: "p",
        text: 'The word "whitening" has fallen out of favour, and rightly so. Healthy skin is not white skin — it is even skin. The goal is not to lighten your natural tone, but to remove the spots, dullness and uneven patches that sit on top of it.',
      },
      { type: "p", text: "True brightening works on three levers:" },
      {
        type: "p",
        text: "1. Reducing melanin overproduction — calming the enzyme (tyrosinase) that drives dark patches",
      },
      {
        type: "p",
        text: "2. Increasing cell turnover — replacing dull, pigment-loaded cells with fresh ones",
      },
      {
        type: "p",
        text: "3. Protecting against new damage — sunscreen, antioxidants, and a quiet life for your skin",
      },
      {
        type: "p",
        text: "A product that hits only one lever will disappoint you. A ritual that hits all three will quietly transform your complexion over a few months.",
      },
      { type: "h2", text: "What actually works — and what doesn't" },
      { type: "h3", text: "Works" },
      {
        type: "p",
        text: "Sunscreen, every single day. This is non-negotiable. Eighty percent of visible ageing in Pakistani skin is sun-driven. SPF 30+ broad spectrum, reapplied if you are outdoors.",
      },
      {
        type: "p",
        text: "Vitamin C in the morning. Brightens, supports collagen, and amplifies sunscreen.",
      },
      {
        type: "p",
        text: "Niacinamide. Calms inflammation, fades pigmentation slowly and safely.",
      },
      {
        type: "p",
        text: "L-Glutathione, taken orally. Works systemically — inhibits melanin production at the cellular level. Pair with vitamin C for compounded effect.",
      },
      {
        type: "p",
        text: "Marine collagen. Restores the structure that pigmentation tends to sit on. Firmer skin reflects light more evenly.",
      },
      { type: "p", text: "Sleep and hydration. Underrated. Skin repair happens at night." },
      { type: "h3", text: "Does not work — or is actively harmful" },
      {
        type: "p",
        text: 'Mercury-based "fairness" creams. Banned for good reason. They cause kidney damage and, ironically, worsen pigmentation long-term.',
      },
      {
        type: "p",
        text: "Aggressive bleaching. Strips the skin barrier, triggers rebound pigmentation, and ages skin faster than it brightens it.",
      },
      {
        type: "p",
        text: '"Detox" teas and miracle drinks. Most are unregulated and have no clinical evidence behind their pigmentation claims.',
      },
      {
        type: "p",
        text: "Hydroquinone over 4 percent without a dermatologist. Effective in the short term, dangerous unsupervised.",
      },
      { type: "h2", text: "A simple, sustainable ritual" },
      {
        type: "p",
        text: "If we had to build the most boring, most effective routine for an average Pakistani woman in her twenties or thirties, it would look like this:",
      },
      { type: "h3", text: "Morning" },
      {
        type: "p",
        text: "Gentle cleanser · Vitamin C serum · Moisturiser · Broad-spectrum SPF 30+ · One vial of an oral glutathione + collagen formula",
      },
      { type: "h3", text: "Evening" },
      {
        type: "p",
        text: "Gentle cleanser · Niacinamide or a gentle retinoid (start twice a week) · Moisturiser",
      },
      {
        type: "p",
        text: "That is it. No ten-step routines, no aggressive acids, no overnight miracles. Done consistently for three months, this routine will visibly even your tone, soften pigmentation, and give you the quiet glow that no harsh product can imitate.",
      },
      { type: "h2", text: "A word on patience" },
      {
        type: "p",
        text: 'The single biggest mistake we see is people stopping after four weeks because "nothing is happening." Pigmentation took years to settle in. It will not unwind in a fortnight. Most people who stick with the ritual above report a clear difference between week six and week twelve, and an obvious one by month four.',
      },
      {
        type: "p",
        text: "Your skin is not broken. It is just asking for the right care, given consistently. Start with the basics, protect it from the sun, support it from within, and let time do the rest.",
      },
    ],
  },
];

export function getPost(slug: string) {
  return posts.find((p) => p.slug === slug);
}
